name: Sync with upstream

on:
  schedule:
    # 每天凌晨 2 点执行
    - cron: '0 2 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configure Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      
      - name: Add upstream
        run: |
          git remote add upstream https://github.com/QuantumNous/new-api.git || true
      
      - name: Fetch upstream
        run: |
          git fetch upstream
      
      - name: Sync main branch
        run: |
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
      
      - name: Create Pull Request for qiyuan-api branch
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-upstream-${{ github.run_number }}
          delete-branch: true
          title: 'Sync: Update from upstream'
          body: |
            This PR updates the qiyuan-api branch with the latest changes from upstream.
            
            Auto-generated by GitHub Actions.
          base: qiyuan-api
          head: main